version = 0.1

[default.build.parameters]
skip_tests = true
[default.deploy.parameters]
stack_name = "woodle"
resolve_s3 = true
s3_prefix = "woodle"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
