AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Woodle Lambda Function using AWS Serverless Java Container

Parameters:
  ApiStageName:
    Type: String
    Default: Prod
    Description: API Gateway stage name used in absolute redirects
  StaticAssetsBucket:
    Type: String
    Default: de.bas.bodo-eu-central-1-168474026156
    Description: S3 bucket to host static assets (images)

Globals:
  Api:
    BinaryMediaTypes:
      - image/jpeg
      - image/png
      - application/octet-stream
      - '*/*'
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        DISABLE_ASYNC_INIT: "true"

Resources:
  StaticAssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: StaticAssetsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowPublicRead
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource:
              Fn::Sub: arn:aws:s3:::${StaticAssetsBucket}/*
  WoodleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.bas.bodo.woodle.StreamLambdaHandler
      Runtime: java21
      Architectures:
        - arm64
      CodeUri: ./
      Policies:
        - S3CrudPolicy:
            BucketName:
              Ref: StaticAssetsBucket
      Environment:
        Variables:
          MAIN_CLASS: de.bas.bodo.woodle.WoodleApplication
          SPRING_PROFILES_ACTIVE: lambda
          API_STAGE:
            Ref: ApiStageName
          AWS_S3_REGION: eu-central-1
          AWS_S3_ACCESS_KEY: ""
          AWS_S3_SECRET_KEY: ""
          AWS_S3_BUCKET_NAME: de.bas.bodo-eu-central-1-168474026156
          AWS_S3_FORCE_PATH_STYLE: true
          STATIC_BASE_URL:
            Fn::Sub: https://s3.${AWS::Region}.amazonaws.com/${StaticAssetsBucket}
      Events:
        RootPath:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

 