AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Woodle Lambda Function using AWS Serverless Java Container

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  WoodleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.serverless.proxy.spring.SpringDelegatingLambdaContainerHandler
      Runtime: java21
      CodeUri: ./
      Environment:
        Variables:
          MAIN_CLASS: de.bas.bodo.woodle.WoodleApplication
          SPRING_PROFILES_ACTIVE: lambda
          AWS_S3_ENDPOINT: ""
          AWS_S3_REGION: us-east-1
          AWS_S3_ACCESS_KEY: ""
          AWS_S3_SECRET_KEY: ""
          AWS_S3_BUCKET_NAME: ""
          AWS_S3_FORCE_PATH_STYLE: true
      Events:
        RootPath:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

 