AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Woodle Lambda Function using AWS Serverless Java Container

Resources:
  WoodleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: woodle
      Handler: com.amazonaws.serverless.proxy.spring.SpringDelegatingLambdaContainerHandler
      Runtime: java21
      MemorySize: 512
      Timeout: 30
      CodeUri: target/woodle-0.0.1-SNAPSHOT.jar
      Environment:
        Variables:
          MAIN_CLASS: de.bas.bodo.woodle.WoodleApplication
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  WoodleLambdaApi:
    Description: "API Gateway endpoint URL for Woodle Lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/" 