AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Woodle Lambda Function using AWS Serverless Java Container

Resources:
  WoodleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: woodle
      Handler: com.amazonaws.serverless.proxy.spring.SpringDelegatingLambdaContainerHandler
      Runtime: java21
      MemorySize: 512
      Timeout: 30
      CodeUri: ./
      Environment:
        Variables:
          MAIN_CLASS: de.bas.bodo.woodle.WoodleApplication
          AWS_S3_ENDPOINT: ""
          AWS_S3_REGION: us-east-1
          AWS_S3_ACCESS_KEY: ""
          AWS_S3_SECRET_KEY: ""
          AWS_S3_BUCKET_NAME: ""
          AWS_S3_FORCE_PATH_STYLE: true
    Events:
      ApiGateway:
        Type: Api
        Properties:
          Path: /{proxy+}
          Method: ANY

 