AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Woodle Lambda Function using AWS Serverless Java Container

Globals:
  Api:
    BinaryMediaTypes:
      - image/jpeg
      - image/png
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        DISABLE_ASYNC_INIT: "true"

Resources:
  WoodleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.bas.bodo.woodle.StreamLambdaHandler
      Runtime: java21
      Architectures:
        - arm64
      CodeUri: ./
      Policies:
        - S3CrudPolicy:
            BucketName: de.bas.bodo-eu-central-1-168474026156
      Environment:
        Variables:
          MAIN_CLASS: de.bas.bodo.woodle.WoodleApplication
          SPRING_PROFILES_ACTIVE: lambda
          AWS_S3_REGION: eu-central-1
          AWS_S3_ACCESS_KEY: ""
          AWS_S3_SECRET_KEY: ""
          AWS_S3_BUCKET_NAME: de.bas.bodo-eu-central-1-168474026156
          AWS_S3_FORCE_PATH_STYLE: true
      Events:
        RootPath:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

 