spring:
  main:
    web-application-type: servlet
    lazy-initialization: true
  cloud:
    function:
      web:
        path-prefix: /
  web:
    resources:
      add-mappings: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Configure for Lambda environment - don't start embedded server
server:
  port: ${PORT:-8080}
  servlet:
    context-path: /

logging:
  level:
    de.bas.bodo.woodle.infrastructure.S3PollStorageService: INFO
    root: INFO
    org.springframework: INFO

# Use precompiled JTE templates in Lambda
gg:
  jte:
    development-mode: false
    use-precompiled-templates: true
  
static:
  base-url: ${STATIC_BASE_URL:}

# AWS S3 Configuration for Lambda (runtime will use execution role; do NOT set keys)
aws:
  s3:
    endpoint: ""            # empty -> use AWS S3 default endpoint
    region: ${AWS_S3_REGION:eu-central-1}
    access-key: ""          # credentials should come from IAM role
    secret-key: ""
    bucket-name: ${AWS_S3_BUCKET_NAME:de.bas.bodo}
    force-path-style: false