spring:
  application:
    name: calendar-lambda
  cloud:
    function:
      web:
        path-prefix: /api
  web:
    resources:
      static-locations: classpath:/static/

gg:
  jte:
    development-mode: true

# AWS S3 Configuration
aws:
  s3:
    endpoint: http://localhost:4566
    region: us-east-1
    access-key: test
    secret-key: test
    bucket-name: de.bas.bodo
    force-path-style: true