spring:
  main:
    web-application-type: servlet
    lazy-initialization: true
  cloud:
    function:
      web:
        path-prefix: /

# Configure for Lambda environment - don't start embedded server
server:
  port: ${PORT:-8080}
  servlet:
    context-path: /

logging:
  level:
    de.bas.bodo.woodle.infrastructure.S3PollStorageService: INFO
    root: DEBUG
    org.springframework: DEBUG

# Use precompiled JTE templates in Lambda
gg:
  jte:
    development-mode: false